/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "square.h"

square_out *
squareproc_1_svc(square_in *argp, struct svc_req *rqstp)
{
	static square_out  result;

	result.res1 = argp->arg1 * argp->arg1;

	return &result;
}
